### ISSUE TITLE
White page in OJS 3.3.0.8

### ISSUE THREAD

**Issue by rcic** [Vitaliy-1/oldGregg#135]
Hello, i'm try to enable this theme in my OJS 3.3.0.8.
But this generate an error in PHP and display White Homepage.

The error is: 
[Fri Feb 04 12:21:11.830586 2022] [php7:error] [pid 919190] [client 94.23.158.223:60233] PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedData() on null in /var/www/ojs3/ucatolica_upgrade/ojs/cache/t_compile/65bfc3e024c2e9104f46e23b73376a9455e3df0e^da5cddfde2ebc97f3525f2500ecb83429bd5fe44_0.app.frontendcomponentsheaderH.php:42\nStack trace:\n#0 /var/www/ojs3/ucatolica_upgrade/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_61fd6087ca54f4_23197191(Object(Smarty_Internal_Template))\n#1 /var/www/ojs3/ucatolica_upgrade/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))\n#2 /var/www/ojs3/ucatolica_upgrade/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))\n#3 /var/www/ojs3/ucatolica_upgrade/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()\n#4 /var/www/ in /var/www/ojs3/ucatolica_upgrade/ojs/cache/t_compile/65bfc3e024c2e9104f46e23b73376a9455e3df0e^da5cddfde2ebc97f3525f2500ecb83429bd5fe44_0.app.frontendcomponentsheaderH.php on line 42

--------------
Please helpme to solve this problem.

**Comment by Vitaliy-1** [comment]
Try to clear the data and template cache and let me know if problem persists

**Comment by bjarman** [comment]
Hi! I get the exact same error when trying to access /index.php on my OJS installation. Accessing a journal, like index.php/my-journal/, works though. I have cleared both data and template cache from within admin but problem persists.

**Comment by Vitaliy-1** [comment]
Just to clarify, you enabled this theme site-wide and using it to display the site index page, right? 
I haven't implemented this feature and recommend on the site level to use another theme for now. I initially thought that this is another issue related to cache.

**Comment by bjarman** [comment]
Ok, so for now I should disable this plugin for webpage and only have it enabled for journal?
