### ISSUE TITLE
I get HTTP ERROR 500, when I try to see the whole article after uploading the XML [OJS 3.1.1]

### ISSUE THREAD

**Issue by varshilmehta** [Vitaliy-1/oldGregg#59]
There is no error if I do not upload the XML file. But if I upload the XML file, I get the error. Error log is as follows:

```
[17-May-2018 17:06:00 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Smarty has a deprecated constructor in /home/u796555399/public_html/journals/openjmri/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php on line 64
[17-May-2018 17:06:00 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADODB_Cache_File has a deprecated constructor in /home/u796555399/public_html/journals/openjmri/lib/pkp/lib/adodb/adodb.inc.php on line 263
[17-May-2018 17:06:00 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADOConnection has a deprecated constructor in /home/u796555399/public_html/journals/openjmri/lib/pkp/lib/adodb/adodb.inc.php on line 359
[17-May-2018 17:06:00 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADORecordSet has a deprecated constructor in /home/u796555399/public_html/journals/openjmri/lib/pkp/lib/adodb/adodb.inc.php on line 2921
[17-May-2018 17:06:00 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADORecordSet_array has a deprecated constructor in /home/u796555399/public_html/journals/openjmri/lib/pkp/lib/adodb/adodb.inc.php on line 3939
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of LensGalleyPlugin::register($category, $path) should be compatible with LazyLoadPlugin::register($category, $path, $mainContextId = NULL) in /home/u796555399/public_html/journals/openjmri/plugins/generic/lensGalley/LensGalleyPlugin.inc.php on line 323
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of PKPUsageEventPlugin::getEnabled() should be compatible with LazyLoadPlugin::getEnabled($contextId = NULL) in /home/u796555399/public_html/journals/openjmri/lib/pkp/plugins/generic/usageEvent/PKPUsageEventPlugin.inc.php on line 386
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of DRIVERDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/u796555399/public_html/journals/openjmri/plugins/generic/driver/DRIVERDAO.inc.php on line 19
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of CustomBlockPlugin::getBlockContext() should be compatible with BlockPlugin::getBlockContext($contextId = NULL) in /home/u796555399/public_html/journals/openjmri/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php on line 134
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of CustomBlockPlugin::getEnabled() should be compatible with BlockPlugin::getEnabled($contextId = NULL) in /home/u796555399/public_html/journals/openjmri/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php on line 134
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai) in /home/u796555399/public_html/journals/openjmri/plugins/generic/openAIRE/OpenAIREDAO.inc.php on line 100
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of ArticleHandler::initialize($request, $args) should be compatible with PKPHandler::initialize($request) in /home/u796555399/public_html/journals/openjmri/pages/article/ArticleHandler.inc.php on line 395
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of SubmissionFileDAO::fromRow($row) should be compatible with PKPSubmissionFileDAO::fromRow($row, $fileImplementation) in /home/u796555399/public_html/journals/openjmri/classes/article/SubmissionFileDAO.inc.php on line 23
[17-May-2018 17:06:00 UTC] PHP Deprecated:  Non-static method PKPApplication::getCCLicenseBadge() should not be called statically in /home/u796555399/public_html/journals/openjmri/pages/article/ArticleHandler.inc.php on line 150
[17-May-2018 17:06:00 UTC] PHP Warning:  Declaration of SubmissionKeywordEntryDAO::getByControlledVocabId($controlledVocabId, $rangeInfo = NULL) should be compatible with ControlledVocabEntryDAO::getByControlledVocabId($controlledVocabId, $rangeInfo = NULL, $filter = NULL) in /home/u796555399/public_html/journals/openjmri/lib/pkp/classes/submission/SubmissionKeywordEntryDAO.inc.php on line 20
[17-May-2018 17:06:00 UTC] PHP Fatal error:  Uncaught TypeError: Return value of JATSParser\Body\Document::extractSections() must be an instance of JATSParser\Body\void, none returned in /home/u796555399/public_html/journals/openjmri/plugins/themes/oldGregg/jatsParser/src/JATSParser/Body/Document.inc.php:122
Stack trace:
#0 /home/u796555399/public_html/journals/openjmri/plugins/themes/oldGregg/jatsParser/src/JATSParser/Body/Document.inc.php(32): JATSParser\Body\Document->extractSections()
#1 /home/u796555399/public_html/journals/openjmri/plugins/themes/oldGregg/OldGreggThemePlugin.inc.php(178): JATSParser\Body\Document->__construct('/home/u79655539...')
#2 /home/u796555399/public_html/journals/openjmri/lib/pkp/classes/plugins/HookRegistry.inc.php(107): OldGreggThemePlugin->jatsParser('TemplateManager...', Array)
#3 /home/u796555399/public_html/journals/openjmri/lib/pkp/classes/template/PKPTemplateManager.inc.php(856): HookRegistry::call('TemplateManager...', Array)
#4 /home/u796555399/public_html/journals/openjmri/pages/article/ArticleHandler.inc.php(19 in /home/u796555399/public_html/journals/openjmri/plugins/themes/oldGregg/jatsParser/src/JATSParser/Body/Document.inc.php on line 122
```

**Comment by Vitaliy-1** [comment]
That's the reason. You need 7.1 minimum. That function that throws an error will work only in PHP 7.1 or higher. https://stackoverflow.com/questions/35482195/php7-void-return-type-not-working

**Comment by varshilmehta** [comment]
Cool. It worked.
